### PR TITLE
Utils - Initial functionality & documentation added

### PR DESCRIPTION
**Pull request by slloyd-src**
Services added and descriptions added to detail.md
Unit tests added
OpenAPI headers added to allow swagger UI to display helpful information
detail.md has details of each specific endpoint

### CODE REVIEW

**Comment by slloyd-src** [comment]
Github's CI build phase currently fails due to org.opencadc:CAOM:2.5.0-SNAPSHOT not being found in the outside world.
* What went wrong:
Failed to notify build listener.
> Could not resolve all artifacts for configuration ':quarkusDevBaseRuntimeClasspathConfiguration'.
   > Could not find org.opencadc:CAOM:2.5.0-SNAPSHOT.
     Required by:
         project :
> There is 1 more failure with an identical cause.

**Review by pahjbo — CHANGES_REQUESTED** [review]
the design of the REST interface end-points is not really what I think of as "standard" - it differs in a couple of ways

* the "verb" is appearing in the URI - this is not necessary - so for instance
`DELETE [/observations/delete/{observationId}]` can just be `DELETE [/observations/{observationId}]`
*  the create and update operations are mapped to the opposite HTTP verbs  than is usual - i.e. the normal thing is create => POST and update => PUT

I think that https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/#h2-2eb87cd076da0 goes over this in a bit more detail


It would be good to just tweak the endpoints to follow that pattern

**Comment by slloyd-src** [comment]
@pahjbo amendments made as requested including the minor changes to the details.md

**Comment by pahjbo** [comment]
I have removed all of the verbs from endpoint URIs - I am not sure that the collections and derivedObservation endpoints are really correct, but will merge for now

**Pull request merged**
